# Generated by Django 3.1.3 on 2020-11-11 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('atr_length', models.FloatField()),
                ('atr_color', models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productcategory')),
            ],
        ),
    ]
