# Generated by Django 3.1.3 on 2020-11-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20201111_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
