# Generated by Django 3.1.3 on 2020-11-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_productcategory_is_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='atr_length',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_root',
            field=models.BooleanField(),
        ),
    ]
