# Generated by Django 3.1.3 on 2020-11-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20201111_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_path',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_root',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
