# Generated by Django 3.1.3 on 2020-11-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20201111_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_path',
            field=models.TextField(default=models.CharField(max_length=50, unique=True), editable=False),
        ),
    ]
