# Generated by Django 3.1.3 on 2020-11-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20201111_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_path',
            field=models.TextField(default='', editable=False),
        ),
    ]
