# Generated by Django 3.1.3 on 2020-11-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_auto_20201111_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_path',
            field=models.TextField(default=models.CharField(max_length=50, unique=True)),
        ),
    ]
