# Generated by Django 3.1.3 on 2020-11-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_auto_20201111_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_path',
        ),
    ]
