# Generated by Django 3.1.3 on 2020-11-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_productcategory_category_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_path',
            field=models.CharField(default=None, editable=False, max_length=300, unique=True),
        ),
    ]
