# Generated by Django 3.1.3 on 2020-11-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_auto_20201111_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='attributes',
            field=models.TextField(default=''),
        ),
    ]
