# Generated by Django 3.1.3 on 2020-11-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_productcategory_attributes_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='attributes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
