# Generated by Django 3.1.3 on 2020-11-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_auto_20201113_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='attributes',
            field=models.TextField(default='', null=True),
        ),
    ]
