# Generated by Django 3.1.3 on 2020-11-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_auto_20201113_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='attributes',
            field=models.TextField(default='puste'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='attributes_old',
            field=models.TextField(default='puste', editable=False),
        ),
    ]
