# Generated by Django 3.1.3 on 2020-11-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0023_auto_20201113_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='attributes_old_json',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='attributes_old',
            field=models.TextField(default='', editable=False),
        ),
    ]
