# Generated by Django 3.1.3 on 2020-11-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0027_auto_20201113_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes_json',
            field=models.JSONField(default={'dane': None}),
        ),
    ]
