# Generated by Django 3.1.3 on 2020-11-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0030_auto_20201113_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='attributes_old_json',
            field=models.JSONField(default=models.JSONField(default=dict), editable=False),
        ),
    ]
