# Generated by Django 3.1.3 on 2020-11-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0031_auto_20201113_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='attributes_old_json',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
