# Generated by Django 3.1.3 on 2020-11-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0033_remove_productcategory_atr_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='attributes_json',
            field=models.JSONField(default={'dane': 'brak'}),
        ),
    ]
