# Generated by Django 3.1.3 on 2020-11-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleProcess', '0004_remove_cart_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='chart_name',
            new_name='cart_name',
        ),
    ]
