# Generated by Django 3.1.3 on 2020-11-15 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SaleProcess', '0005_auto_20201115_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_name',
            field=models.CharField(default='domyślny', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
