# Generated by Django 3.1.3 on 2020-11-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleProcess', '0009_auto_20201115_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_name',
            field=models.CharField(default='domyślny', max_length=100),
        ),
    ]
